// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:CareerPortal/DAL/Migrations/202305152009326_DbInit.Designer.cs
    public sealed partial class DbInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202305152009326_DbInit"; }
========
    public sealed partial class AddToDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddToDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202305151846264_AddToDatabase"; }
>>>>>>>> 0e61077f4ee42d6daa9d8df37d99ee495734e742:CareerPortal/DAL/Migrations/202305151846264_AddToDatabase.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
