// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:CareerPortal/DAL/Migrations/202304271437273_DbInit.Designer.cs
    public sealed partial class DbInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202304271437273_DbInit"; }
========
    public sealed partial class InitDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202304271436385_InitDatabase"; }
>>>>>>>> fa832b9aa173802a0df0fabd61c032030c8d9690:CareerPortal/DAL/Migrations/202304271436385_InitDatabase.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
